export const AUTH_STATUS_AUTHENTICATED = 'AUTH_STATUS_AUTHENTICATED'
export const AUTH_STATUS_NOT_AUTHENTICATED = 'AUTH_STATUS_NOT_AUTHENTICATED'
export const AUTH_STATUS_IS_LOGOUTED = 'AUTH_STATUS_IS_LOGOUTED'
