export const STARTING_MONTH_IN_SCHEDULE = 7
export const STARTING_DATE_OF_MONTH_IN_SCHEDULE = 1
export const END_MONTH_IN_SCHEDULE = 6
export const END_DATE_OF_MONTH_IN_SCHEDULE = 30
export const DAYS_RANGE_FOR_LEARNING_DATE = 30
